---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexify
  labels:
    {{- include "labels" (dict "name" "indexify" "component" "config" "global" $) | nindent 4 }}
data:
  config.yaml: |-
    coordinator_addr: coordinator:8950
    raft_port: 8970
    seed_node: localhost:8970
    node_id: 0

    state_store:
      path: /data/state

    db_url: {{ .Values.dbURL }}
    index_config:
      {{- .Values.indexConfig | toYaml | nindent 6 }}
    metadata_storage:
      {{- .Values.metadataStorage | toYaml | nindent 6 }}

    blob_storage:
      {{- .Values.blobStore.config | toYaml | nindent 6 }}
