{{- range $i, $e := until (.Values.coordinator.replicaCount | int) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.coordinator.name }}-config-{{ $i }}
  labels:
    {{- include "labels" (dict "name" .Values.coordinator.name "component" "config" "global" $) | nindent 4 }}
data:
  config.yaml: |-
    coordinator_addr: {{ .Values.coordinator.serviceName }}:8950
    raft_port: 8970
    seed_node: {{ .Values.coordinator.serviceName }}-0.{{ .Values.coordinator.serviceName }}.{{ .Values.namespace }}.svc.cluster.local:8970
    node_id: {{ $i }}
    state_store:
      path: /data/state
    db_url: {{ .Values.coordinator.dbURL }}
    index_config:
      {{- .Values.coordinator.indexConfig | toYaml | nindent 6 }}
    metadata_storage:
      {{- .Values.coordinator.metadataStorage | toYaml | nindent 6 }}
    blob_storage:
      {{- .Values.coordinator.blobStore.config | toYaml | nindent 6 }}
{{- end }}