{{- with .Values.coordinator }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  ports:
    - port: 8950
  selector:
    {{- include "labels" (dict "name" "coordinator" "component" "coordinator" "global" $) | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.coordinator.name }}
  labels:
    {{- include "labels" (dict "name" .Values.coordinator.name "component" "coordinator" "global" $) | nindent 4 }}
spec:
  serviceName: {{ .Values.coordinator.serviceName }}
  replicas: {{ .Values.coordinator.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.coordinator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.coordinator.name }}
    spec:
      containers:
        - name: indexify
          image: {{ .Values.coordinator.image }}
          command: ['indexify']
          args:
            - coordinator
            - --config-path
            - /etc/coordinator/config.yaml
          volumeMounts:
            - mountPath: /etc/coordinator
              name: config
              readOnly: true
            - mountPath: /data
              name: data
      volumes:
        - name: config
          configMap:
            name: {{ .Values.coordinator.name }}-config-{{ .pod.name }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
