{{- with .Values.coordinator }}
{{- if .enabled }}
{{- $statefulsetName := .name }}
{{- $replicaCount := .replicaCount | default 1 }}
{{- range $i, $e := until $replicaCount }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $statefulsetName }}-config-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels" (dict "name" $statefulsetName "component" "config" "global" $) | nindent 4 }}
data:
  config.yaml: |-
    coordinator_addr: {{ $statefulsetName }}-0.{{ $statefulsetName }}.{{ $.Release.Namespace }}.svc.cluster.local:8950
    raft_port: 8970
    seed_node: {{ $statefulsetName }}-0.{{ $statefulsetName }}.{{ $.Release.Namespace }}.svc.cluster.local:8970
    node_id: {{ $i }}
    state_store:
      path: /data/state
    db_url: {{ $.Values.dbURL }}
    index_config:
      {{- $.Values.indexConfig| toYaml | nindent 6 }}
    metadata_storage:
      {{- $.Values.metadataStorage | toYaml | nindent 6 }}
    blob_storage:
      {{- $.Values.blobStore.config | toYaml | nindent 6 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  ports:
    - port: 8950
  selector:
    {{- include "labels" (dict "name" "coordinator" "component" "coordinator" "global" $) | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name }}
  labels:
    {{- include "labels" (dict "name" .name "component" "coordinator" "global" $) | nindent 4 }}
spec:
  serviceName: {{ .name }}
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: indexify
          image: {{ .image }}
          command: ['indexify']
          args:
            - coordinator
            - --config-path
            - /etc/coordinator/config.yaml
          volumeMounts:
            {{- range $i, $e := until $replicaCount }}
            - mountPath: /etc/coordinator
              name: config-{{ $i }}
              readOnly: true
            {{- end }}
            - mountPath: /data
              name: data
      volumes:
        {{- range $i, $e := until $replicaCount }}
        - name: config-{{ $i }}
          configMap:
            name: {{ $statefulsetName }}-config-{{ $i }}
        {{- end }}
        - name: data
          emptyDir: {}
{{- end }}
{{- end }}